<div class="page-header">
    <h1>Subir base inicial de Inventario</h1>
</div>
<?php echo $this->tag->form(array("subir/upload",  'enctype' => 'multipart/form-data')); ?>

<table>
<tbody>
<tr>
	<td>Archivo</td>
	<td><?php echo $this->tag->fileField("archivo") ?></td>
</tr>
<tr>
	<td colspan="2"><?php echo $this->tag->submitButton("Subir Bien llevado a Gasto") ?></td>
</tr>
</tbody>
</table>

</form>

<?php echo $this->tag->form(array("subir/uploadAF",  'enctype' => 'multipart/form-data')); ?>

<table>
<tbody>
<tr>
	<td>Archivo</td>
	<td><?php echo $this->tag->fileField("archivo2") ?></td>
</tr>
<tr>
	<td colspan="2"><?php echo $this->tag->submitButton("Subir Activo Fijo") ?></td>
</tr>
</tbody>
</table>

</form>