<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("menu", "Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit menu
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "menu/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldMId" class="col-sm-2 control-label">M</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("m_id", "size" => 30, "class" => "form-control", "id" => "fieldMId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMLabel" class="col-sm-2 control-label">M Of Label</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("m_label", "size" => 30, "class" => "form-control", "id" => "fieldMLabel")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMHref" class="col-sm-2 control-label">M Of Href</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("m_href", "size" => 30, "class" => "form-control", "id" => "fieldMHref")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMParent" class="col-sm-2 control-label">M Of Parent</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("m_parent", "size" => 30, "class" => "form-control", "id" => "fieldMParent")) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
