<div class="page-header">
    <h1>Activo Fijo</h1>
</div>
<?php 
echo $this->getContent();
?>
<script type="text/javascript" language="javascript" class="init">
	$(document).ready(function() {
		$('#activos').DataTable({
			"footerCallback": function ( row, data, start, end, display ) {
	            var api = this.api(), data;
	 
	            // Remove the formatting to get integer data for summation
	            var intVal = function ( i ) {
	                return typeof i === 'string' ?
	                    i.replace(/[\$,]/g, '')*1 :
	                    typeof i === 'number' ?
	                        i : 0;
	            };
	 
	            // Total over all pages
	            total = api
	                .column( 6 )
	                .data()
	                .reduce( function (a, b) {
	                    return intVal(a) + intVal(b);
	                }, 0 );
	 
	            // Total over this page
	            pageTotal = api
	                .column( 6, { page: 'current'} )
	                .data()
	                .reduce( function (a, b) {
	                    return intVal(a) + intVal(b);
	                }, 0 );
	 
	            // Update footer
	            $( api.column( 5 ).footer() ).html(
	                'Valor Adquisi&oacute;n por hoja: $'+pageTotal.toFixed(2) +' (Total: $'+ total.toFixed(2) + ')'
	            );
	        }
		});
	} );
</script>
<div id="tdiv" style="font-size:0.7em;">
<table id="activos" class="display" cellspacing="0" width="100%" >
<thead><tr>
	<th>Correlativo</th>
	<th>Descripcion</th>
	<th>Ubicaci&oacute;n</th>
	<th>Usuario</th>
	<th>Observaciones</th>
	<th>Fecha Ingreso</th>
	<th>Valor Adquisici&oacute;n</th>
	<th>Valor Residual</th>
	<th>Deprec. Acumulada</th>
	<th>Pend. Depreciar</th>
	<th>Acciones</th>	
</tr></thead>
<tfoot>
	<tr>
        <th colspan="10" style="text-align:right">Total:</th>    	
	</tr>
</tfoot>
<tbody>
<?php
	$bienesList = Inventario::find("i_activo = 1 and i_estado = 1");
	foreach ($bienesList as $bien){
		echo "<tr>";
		echo "<td>$bien->i_correlativo</td>";
		echo "<td>$bien->i_descripcion</td>";
		$ubicacion = "";
		if($bien->ubicid != null && $bien->ubicid != ""){
			$ubic = Ubicacion::findFirst("ub_id = $bien->ubicid");
			$ubicacion = $ubic->ub_nombre;
		}
		echo "<td>$ubicacion</td>";
		$usuario = "";
		if($bien->u_id != null && $bien->u_id != ""){
			$user = Usuarios::findFirst("u_id = $bien->u_id");
			$usuario = $user->u_lanid;
		}
		echo "<td>$usuario</td>";
		echo "<td>$bien->i_observaciones</td>";
		echo "<td>$bien->i_fingreso</td>";
		echo "<td>$ ".number_format($bien->i_vadquisicion,2)."</td>";
		echo "<td>$ ".number_format($bien->i_vresidual,2)."</td>";
		echo "<td>$ ".number_format($bien->i_dacumulada,2)."</td>";
		echo "<td>$ ".number_format($bien->i_penddepreciar,2)."</td>";
		$cb = new ControllerBase();
		echo "<td>".$cb->a(1, "inventario/editInventario", "Editar", [["id",$bien->i_id]])."</td>";
		echo "</tr>";
	}
?>
</tbody>
</table>
</div>