<div class="page-header">
    <h1>Bienes llevados a gasto</h1>
</div>
<script type="text/javascript" language="javascript" class="init">
	$(document).ready(function() {
		$('#bienes').DataTable({
			"footerCallback": function ( row, data, start, end, display ) {
	            var api = this.api(), data;
	 
	            // Remove the formatting to get integer data for summation
	            var intVal = function ( i ) {
	                return typeof i === 'string' ?
	                    i.replace(/[\$,]/g, '')*1 :
	                    typeof i === 'number' ?
	                        i : 0;
	            };
	 
	            // Total over all pages
	            total = api
	                .column( 6 )
	                .data()
	                .reduce( function (a, b) {
	                    return intVal(a) + intVal(b);
	                }, 0 );
	 
	            // Total over this page
	            pageTotal = api
	                .column( 6, { page: 'current'} )
	                .data()
	                .reduce( function (a, b) {
	                    return intVal(a) + intVal(b);
	                }, 0 );
	 
	            // Update footer
	            $( api.column( 4 ).footer() ).html(
	                'Valor Adquisi&oacute;n por hoja: $'+pageTotal.toFixed(2) +' (Total: $'+ total.toFixed(2) + ')'
	            );
	        }
		});
	} );
</script>
<div id="tdiv" style="font-size:0.7em;">
<table id="bienes" class="display" cellspacing="0" width="100%" >
<thead><tr>
	<th>Correlativo</th>
	<th>Descripcion</th>
	<th>Ubicaci&oacute;n</th>
	<th>Usuario</th>
	<th>Observaciones</th>
	<th>Fecha Ingreso</th>
	<th>Valor Adquisici&oacute;n</th>	
</tr></thead>
<tfoot>
	<tr>
        <th colspan="7" style="text-align:right">Total:</th>    	
	</tr>
</tfoot>
<tbody>
<?php
	$bienesList = Inventario::find("i_activo = 2 and i_estado = 1");
	foreach ($bienesList as $bien){
		echo "<tr>";
		echo "<td>$bien->i_correlativo</td>";
		echo "<td>$bien->i_descripcion</td>";
		echo "<td>$bien->i_ubicacion</td>";
		$users = Usuarios::find("u_id = $bien->u_id");
		foreach ($users as $user){
			echo "<td>$user->u_nombre</td>";
		}		
		echo "<td>$bien->i_observaciones</td>";
		echo "<td>$bien->i_fingreso</td>";
		echo "<td>$ ".number_format($bien->i_vadquisicion,2)."</td>";		
		echo "</tr>";
	}
?>
</tbody>
</table>
</div>