<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("inventario/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("inventario/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>I</th>
            <th>I Of Correlativo</th>
            <th>I Of Descripcion</th>
            <th>I Of Uanterior</th>
            <th>I Of Fingreso</th>
            <th>I Of Vadquisicion</th>
            <th>I Of Vresidual</th>
            <th>I Of Dacumulada</th>
            <th>I Of Penddepreciar</th>
            <th>I Of Encontrado</th>
            <th>I Of Observaciones</th>
            <th>I Of Ubicacion</th>
            <th>U</th>
            <th>I Of Activo</th>
            <th>I Of Serie</th>
            <th>I Of Modelo</th>
            <th>I Of Marca</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $inventario): ?>
            <tr>
                <td><?php echo $inventario->i_id ?></td>
            <td><?php echo $inventario->i_correlativo ?></td>
            <td><?php echo $inventario->i_descripcion ?></td>
            <td><?php echo $inventario->i_uanterior ?></td>
            <td><?php echo $inventario->i_fingreso ?></td>
            <td><?php echo $inventario->i_vadquisicion ?></td>
            <td><?php echo $inventario->i_vresidual ?></td>
            <td><?php echo $inventario->i_dacumulada ?></td>
            <td><?php echo $inventario->i_penddepreciar ?></td>
            <td><?php echo $inventario->i_encontrado ?></td>
            <td><?php echo $inventario->i_observaciones ?></td>
            <td><?php echo $inventario->i_ubicacion ?></td>
            <td><?php echo $inventario->u_id ?></td>
            <td><?php echo $inventario->i_activo ?></td>
            <td><?php echo $inventario->i_serie ?></td>
            <td><?php echo $inventario->i_modelo ?></td>
            <td><?php echo $inventario->i_marca ?></td>

                <td><?php echo $this->tag->linkTo(array("inventario/edit/" . $inventario->i_id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("inventario/delete/" . $inventario->i_id, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("inventario/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("inventario/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("inventario/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("inventario/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
