<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search ubicacion
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("ubicacion/new", "Create ubicacion")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "ubicacion/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldUbId" class="col-sm-2 control-label">Ub</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("ub_id", "size" => 30, "class" => "form-control", "id" => "fieldUbId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUbNombre" class="col-sm-2 control-label">Ub Of Nombre</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("ub_nombre", "size" => 30, "class" => "form-control", "id" => "fieldUbNombre")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUbDescripcion" class="col-sm-2 control-label">Ub Of Descripcion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("ub_descripcion", "size" => 30, "class" => "form-control", "id" => "fieldUbDescripcion")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Search", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
