<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("usuarios/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("usuarios/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>U</th>
            <th>U Of Nombre</th>
            <th>U Of Apellido</th>
            <th>U Of Lanid</th>
            <th>U Of Contrasena</th>
            <th>U Of Creacion</th>
            <th>U Of Modificacion</th>
            <th>U Of Estado</th>
            <th>U Of Codigo</th>
            <th>U Of Eid</th>
            <th>D</th>
            <th>U Of Tipo</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $usuario): ?>
            <tr>
                <td><?php echo $usuario->u_id ?></td>
            <td><?php echo $usuario->u_nombre ?></td>
            <td><?php echo $usuario->u_apellido ?></td>
            <td><?php echo $usuario->u_lanid ?></td>
            <td><?php echo $usuario->u_contrasena ?></td>
            <td><?php echo $usuario->u_creacion ?></td>
            <td><?php echo $usuario->u_modificacion ?></td>
            <td><?php echo $usuario->u_estado ?></td>
            <td><?php echo $usuario->u_codigo ?></td>
            <td><?php echo $usuario->u_eid ?></td>
            <td><?php echo $usuario->d_id ?></td>
            <td><?php echo $usuario->u_tipo ?></td>

                <td><?php echo $this->tag->linkTo(array("usuarios/edit/" . $usuario->u_id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("usuarios/delete/" . $usuario->u_id, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("usuarios/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("usuarios/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("usuarios/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("usuarios/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
