<script type="text/javascript">
$(document).ready(function() {
	$('.date').mask('0000-00-00');
	$('.datepicker').pickadate();

	$("#fieldInventario").keydown(function (e) {
	   if (e.which == 9 || e.keyCode === 9){
		   $.ajax({
				type: "POST",
				url: "formulario/loadItem", 
				data: {inventario: $('#fieldInventario').val()},
				dataType: "json",
				success: function(result){
					var jsondata = jQuery.parseJSON(JSON.stringify(result));
					$("#fieldTipo").val(jsondata.a);
					$("#fieldDesc").val(jsondata.b);
					$("#fieldMarca").val(jsondata.c);
					$("#fieldModelo").val(jsondata.d);
					$("#fieldColor").val(jsondata.e);
					$("#fieldSerie").val(jsondata.f);
					$("#fieldOtros").val(jsondata.g);
				}				
			});
	   }
	});
});

</script>


<div class="page-header">
    <h1>
        Formulario para Baja de Activo o Bien llevado a Gasto
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "formulario/bajar",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>
<!-- Single button -->
<div class="btn-group topNot">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  <i class="fa fa-newspaper-o"></i>
  </button>
  <ul class="dropdown-menu">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
    <li role="separator" class="divider"></li>
    <li><a href="#">Separated link</a></li>
  </ul>
</div>

<div class="form-group">
    <label for="fieldFFecha" class="col-sm-2 control-label">Fecha</label>
    <div class="col-sm-2 control-label">
        <?php echo $fecha;?>
    </div>
</div>
<h2>
	Descripci&oacute;n del Activo o Bien
</h2>
<div class="form-group">
    <label for="fieldInventario" class="col-sm-2 control-label">No. Inventario</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("inventario", "size" => 30, "class" => "form-control", "id" => "fieldInventario")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldTipo" class="col-sm-2 control-label">Tipo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tipo", "size" => 30, "class" => "form-control", "id" => "fieldTipo")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldDesc" class="col-sm-2 control-label">Descripci&oacute;n</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("desc", "size" => 30, "class" => "form-control", "id" => "fieldDesc")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldMarca" class="col-sm-2 control-label">Marca</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("marca", "size" => 30, "class" => "form-control", "id" => "fieldMarca")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldModelo" class="col-sm-2 control-label">Modelo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("modelo", "size" => 30, "class" => "form-control", "id" => "fieldModelo")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldColor" class="col-sm-2 control-label">Color</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("color", "size" => 30, "class" => "form-control", "id" => "fieldColor")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldSerie" class="col-sm-2 control-label">Serie</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("serie", "size" => 30, "class" => "form-control", "id" => "fieldSerie")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldOtros" class="col-sm-2 control-label">Otros</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("otros", "size" => 30, "class" => "form-control", "id" => "fieldOtros")) ?>
    </div>
</div>
<div class="line"></div>
<h2>
	Datos Baja
</h2>
<div class="form-group">
    <label for="fieldMotivo" class="col-sm-2 control-label">Motivo de Baja</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("motivo", "size" => 30, "class" => "form-control", "id" => "motivo")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldFechaB" class="col-sm-2 control-label">Fecha de Baja</label>
    <div class="col-sm-10">
        <?php echo $this->tag->dateField(array("fechaB", "min" => "0", "size" => 30, "class" => "form-control date datepicker", "id" => "fieldFechaB")) ?>
    </div>
</div>
<div class="form-group">
    <label for="accion" class="col-sm-2 control-label">Acci&oacute;n a tomar:</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("accion", "size" => 30, "class" => "form-control", "id" => "accion")) ?>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-1 col-sm-10">
        <?php echo $this->tag->submitButton(array("Bajar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
