<script type="text/javascript">
$(document).ready(function() {
	$('.date').mask('0000-00-00');
	$('.datepicker').pickadate();

	$("#inventario").keydown(function (e) {
	   if (e.which == 9 || e.keyCode === 9){
		   $.ajax({
				type: "POST",
				url: "formulario/loadItem", 
				data: {inventario: $('#inventario').val()},
				dataType: "json",
				success: function(result){
					var jsondata = jQuery.parseJSON(JSON.stringify(result));
					$("#tipo").val(jsondata.a);
					$("#desc").val(jsondata.b);
					$("#marca").val(jsondata.c);
					$("#modelo").val(jsondata.d);
					$("#color").val(jsondata.e);
					$("#serie").val(jsondata.f);
					$("#otros").val(jsondata.g);
				}				
			});
	   }
	});
});


</script>
<?php
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
?>
