<script type="text/javascript">
$(document).ready(function() {
	$(function() {
	    var $radios = $('input:radio[name=asignar]');
	    $radios.filter('[value=Usuario]').prop('checked', true);
	    $('#ubic').prop('disabled', true);
	});
	
	$('#dept').change(function() {
		var dis = 0;
		var $radios = $('input:radio[value=Departamento]');
		if($radios.is(':checked') === true) {
			dis = 1;
		}
		$.ajax({
			type: "POST",
			url: "formulario/listUsers", 
			data: {dept: $('#dept').val(), disable: dis},
			dataType: "json",
			success: function(result){
				var jsondata = jQuery.parseJSON(JSON.stringify(result)); 
				$("#udiv").html(jsondata.select);
			}});
	});

	$('#Usuario').click(function() {		
		$('#user').prop('disabled', false);	
		$('#ubic').prop('disabled', true);				
	});
	$('#Departamento').click(function() {		
		$('#user').prop('disabled', true);
		$('#ubic').prop('disabled', false);			
	});
});

</script>

<?php 
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
?>