<script type="text/javascript">
$(document).ready(function() {
	$('#fieldDept').change(function() {
		//alert("ingreso paso 2");
		$.ajax({
			type: "POST",
			url: "formulario/listUsers", 
			data: {dept: $('#fieldDept').val()},
			dataType: "json",
			success: function(result){
				var jsondata = jQuery.parseJSON(JSON.stringify(result)); 
				$("#udiv").html(jsondata.select);
			}});
	});

	$('.date').mask('0000-00-00');
	$('.datepicker').pickadate();
});

</script>


<div class="page-header">
    <h1>
        Formulario para Nuevo Activo o Bien llevado a Gasto
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "formulario/guardarNuevo",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldFFecha" class="col-sm-2 control-label">Fecha</label>
    <div class="col-sm-2 control-label">
        <?php echo $fecha;?>
    </div>
</div>
<h2>
	Descripci&oacute;n del Activo o Bien
</h2>
<div class="form-group">
    <label for="fieldTipo" class="col-sm-2 control-label">Tipo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tipo", "size" => 30, "class" => "form-control", "id" => "fieldTipo")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldDesc" class="col-sm-2 control-label">Descripci&oacute;n</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("desc", "size" => 30, "class" => "form-control", "id" => "fieldDesc")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldMarca" class="col-sm-2 control-label">Marca</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("marca", "size" => 30, "class" => "form-control", "id" => "fieldMarca")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldModelo" class="col-sm-2 control-label">Modelo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("modelo", "size" => 30, "class" => "form-control", "id" => "fieldModelo")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldColor" class="col-sm-2 control-label">Color</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("color", "size" => 30, "class" => "form-control", "id" => "fieldColor")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldSerie" class="col-sm-2 control-label">Serie</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("serie", "size" => 30, "class" => "form-control", "id" => "fieldSerie")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldOtros" class="col-sm-2 control-label">Otros</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("otros", "size" => 30, "class" => "form-control", "id" => "fieldOtros")) ?>
    </div>
</div>
<div class="line"></div>
<h2>
	Datos Ingreso
</h2>
<div class="form-group">
    <label for="fieldProveedor" class="col-sm-2 control-label">Proveedor</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("proveedor", "size" => 30, "class" => "form-control", "id" => "fieldProveedor")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldValor" class="col-sm-2 control-label">Valor</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("valor", "min" => "0", "size" => 30, "class" => "form-control", "id" => "fieldValor")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldDept" class="col-sm-2 control-label">Departamento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(array("dept",
		    Departamento::find(),
		    "using" => array("d_id", "d_nombre"), "class" => "form-control", "id" => "fieldDept")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldUser" class="col-sm-2 control-label">Usuario</label>
    <div class="col-sm-10" id="udiv">
        <?php
        	$d= Departamento::find(array("limit" => 1));
        	foreach ($d as $did){
        		echo $this->tag->select(array("user", 
        				Usuarios::find("u_estado = 1 AND d_id = $did->d_id"),
        				"using" => array("u_id", "u_nombre"), "class" => "form-control", "id" => "fieldUser")); 
        	}
        		?>
        	
    </div>
</div>
<div class="form-group">
    <label for="fieldDoc" class="col-sm-2 control-label">Documento No.</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("doc", "min" => "0", "size" => 30, "class" => "form-control", "id" => "fieldDoc")) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldFechaC" class="col-sm-2 control-label">Fecha compra</label>
    <div class="col-sm-10">
        <?php echo $this->tag->dateField(array("fechaC", "min" => "0", "size" => 30, "class" => "form-control date datepicker", "id" => "fieldFechaC")) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-1 col-sm-10">
        <?php echo $this->tag->submitButton(array("Ingresar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
