<link rel="stylesheet" type="text/css" href="css/elements.css">
<script type="text/javascript">
$(document).ready(function() {
	$('#inv').DataTable();
	var hoy = new Date();
	$('#mes').val(hoy.getMonth()+1);	
});
</script>
<?php 
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
?>
<nobr>&nbsp;</nobr>
<div id="tdiv">
<table id="inv" class="display" cellspacing="0">
<thead><tr>
	<th>Formulario</th>
	<th>Tipo</th>
	<th>Fecha</th>
	<th>Inventario</th>
	<th>Serie</th>
	<th>Proveedor</th>
	<th>Movimiento</th>	
	<th>Valor Adquisici&oacute;n</th>
	<th>Acciones</th>				
</tr></thead>
<tbody>
<?php
	$search = $this->session->get("search");
	if($search != null && $search != ""){
		$flist = Formulario::find(array($search));
	}else{
		$actual = date("Y-m");
		$flist = Formulario::find(array("f_fecha > '$actual'"));//date_format(current_date, '%Y-%m'");
	}
	//echo "<tr><td colspan='9'>$actual</td></tr>";
	foreach ($flist as $f){
		echo "<tr>";
		echo "<td>$f->f_correlativo</td>";
		echo "<td>";
		if($f->f_tipoinventario == 1){
			echo "Activo Fijo";
		}else echo "Gasto";
		echo "</td>";
		echo "<td>".date("Y-m-d",strtotime($f->f_fecha))."</td>";
		$inv = Inventario::findFirst("i_id = $f->i_id");		
		echo "<td>$inv->i_correlativo</td>";
		echo "<td>$inv->i_serie</td>";
		echo "<td>$inv->i_proveedor</td>";
		echo "<td>";
		if($f->f_movimiento == 1){
			echo "Ingreso";
		}elseif ($f->f_movimiento == 2){
			echo "Traslado";
		}else echo "Baja";
		echo "</td>";
		echo "<td>$ ".number_format($inv->i_vadquisicion,2)."</td>";
		echo "<td><a href='formulario/reimprime2?c=$f->f_correlativo&t=$f->f_tipoinventario'>Reimprimir</a></td>";
		echo "</tr>";
	}
?>
</tbody>
</table>
</div>

<div id="pop">
<!-- Popup Div Starts Here -->
<div id="popupCorr">
<!-- AgregaCorr Popup -->
<?php
    echo $this->tag->form(
        array(
            "inventario/agregaCorr",
            "autocomplete" => "off",
            "class" => "form-horizontal",
        	"id" => "popf"
        )
    );
    /*
     <hr>

    <div class="form-group">
    <div class="col-sm-2">
    </div>
</div>
<div class="form-group">
    <div class="col-sm-2">
    </div>
</div>

     */
?>
<img id="close" src="images/x.png" onclick ="div_hide()">
<hr>
<h2>Agregar Correlativo</h2>
<div class="form-group">
    <div class="col-sm-12" id="serie">
        
    </div>
</div>
<div class="form-group">
    <div class="col-sm-12">
        <?php echo $this->tag->textField(array("corr", "size" => 30, "class" => "form-control", "id" => "fcorr")) ?>
    </div>
</div>
<?php echo $this->tag->hiddenField(array("iid", "size" => 30, "class" => "form-control", "id" => "fiid")) ?>
<div class="form-group">
    <div class="col-sm-12">
        <?php echo $this->tag->submitButton(array("Agregar", "class" => "btn btn-default")) ?>
    </div>
</div>
<?php echo $this->tag->endForm(); ?>
</div>
<!-- Popup Div Ends Here -->
</div>