<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("formulario/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("formulario/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>F</th>
            <th>F Of Fecha</th>
            <th>I</th>
            <th>F Of Movimiento</th>
            <th>F Of Documento</th>
            <th>F Of Proveedor</th>
            <th>F Of Uanterior</th>
            <th>F Of Fechacompra</th>
            <th>F Of Adept</th>
            <th>F Of Ndept</th>
            <th>F Of Unuevo</th>
            <th>F Of Fechamov</th>
            <th>F Of Motivobaja</th>
            <th>F Of Elaboradopor</th>
            <th>F Of Autorizadopor</th>
            <th>F Of Personaconta</th>
            <th>F Of Fecharevisado</th>
            <th>F Of Correlativo</th>
            <th>F Of Tipoinventario</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $formulario): ?>
            <tr>
                <td><?php echo $formulario->f_id ?></td>
            <td><?php echo $formulario->f_fecha ?></td>
            <td><?php echo $formulario->i_id ?></td>
            <td><?php echo $formulario->f_movimiento ?></td>
            <td><?php echo $formulario->f_documento ?></td>
            <td><?php echo $formulario->f_proveedor ?></td>
            <td><?php echo $formulario->f_uanterior ?></td>
            <td><?php echo $formulario->f_fechacompra ?></td>
            <td><?php echo $formulario->f_adept ?></td>
            <td><?php echo $formulario->f_ndept ?></td>
            <td><?php echo $formulario->f_unuevo ?></td>
            <td><?php echo $formulario->f_fechamov ?></td>
            <td><?php echo $formulario->f_motivobaja ?></td>
            <td><?php echo $formulario->f_elaboradopor ?></td>
            <td><?php echo $formulario->f_autorizadopor ?></td>
            <td><?php echo $formulario->f_personaconta ?></td>
            <td><?php echo $formulario->f_fecharevisado ?></td>
            <td><?php echo $formulario->f_correlativo ?></td>
            <td><?php echo $formulario->f_tipoinventario ?></td>

                <td><?php echo $this->tag->linkTo(array("formulario/edit/" . $formulario->f_id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("formulario/delete/" . $formulario->f_id, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("formulario/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("formulario/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("formulario/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("formulario/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
