<script type="text/javascript">
$(document).ready(function() {
	$(function() {
	    var $radios = $('input:radio[name=asignar]');
	    $radios.filter('[value=Usuario]').prop('checked', true);
	    $('#ubic').prop('disabled', true);
	});
	
	$('#dept').change(function() {
		var dis = 0;
		var $radios = $('input:radio[value=Departamento]');
		if($radios.is(':checked') === true) {
			dis = 1;
		}
		$.ajax({
			type: "POST",
			url: "formulario/listUsers", 
			data: {dept: $('#dept').val(), disable: dis},
			dataType: "json",
			success: function(result){
				var jsondata = jQuery.parseJSON(JSON.stringify(result)); 
				$("#udiv").html(jsondata.select);				
			}});
	});

	$("#inventario").keydown(function (e) {
	   if (e.which == 9 || e.keyCode === 9){
		   $.ajax({
				type: "POST",
				url: "formulario/loadItem", 
				data: {inventario: $('#inventario').val()},
				dataType: "json",
				success: function(result){
					var jsondata = jQuery.parseJSON(JSON.stringify(result));
					$("#tipo").val(jsondata.a);
					$("#desc").val(jsondata.b);
					$("#marca").val(jsondata.c);
					$("#modelo").val(jsondata.d);
					$("#color").val(jsondata.e);
					$("#serie").val(jsondata.f);
					$("#otros").val(jsondata.g);
					$("#aubic").val(jsondata.aubic);
					$("#da").val(jsondata.da);
					$("#ua").val(jsondata.u);
				}				
			});
	   }
	});

	$('#Usuario').click(function() {		
		$('#user').prop('disabled', false);	
		$('#ubic').prop('disabled', true);				
	});
	$('#Departamento').click(function() {		
		$('#user').prop('disabled', true);
		$('#ubic').prop('disabled', false);			
	});		
});

</script>

<?php 
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
?>