<script type="text/javascript">
$(document).ready(function() {
	$('#dept').change(function() {
		//alert("ingreso paso 2");
		$.ajax({
			type: "POST",
			url: "formulario/listUsers", 
			data: {dept: $('#dept').val()},
			dataType: "json",
			success: function(result){
				var jsondata = jQuery.parseJSON(JSON.stringify(result)); 
				$("#udiv").html(jsondata.select);
			}});
	});

	$("#inventario").keydown(function (e) {
	   if (e.which == 9 || e.keyCode === 9){
		   $.ajax({
				type: "POST",
				url: "formulario/loadItem", 
				data: {inventario: $('#inventario').val()},
				dataType: "json",
				success: function(result){
					var jsondata = jQuery.parseJSON(JSON.stringify(result));
					$("#tipo").val(jsondata.a);
					$("#desc").val(jsondata.b);
					$("#marca").val(jsondata.c);
					$("#modelo").val(jsondata.d);
					$("#color").val(jsondata.e);
					$("#serie").val(jsondata.f);
					$("#otros").val(jsondata.g);
					$("#da").val(jsondata.de);
					$("#ua").val(jsondata.u);
				}				
			});
	   }
	});

	$('#Usuario').click(function() {		
		$('#user').prop('disabled', false);			
	});
	$('#Departamento').click(function() {		
		$('#user').prop('disabled', true);			
	});		
});

</script>

<?php 
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
?>