<script type="text/javascript">
$(document).ready(function() {
	$('.edit').hide();		
});
<?php 
//	echo $this->view->js;
?>
</script>
<?php 
/*echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
echo $this->view->botones;
echo $this->view->tabla;*/
?>

<style type="text/css">
<!--
@page {
	margin: 10px
}

@font-face {
  font-family: "AIGFutura";
  src: url("font/AIGFutura-Medium.otf") format("opentype");
}
h2{
	font-family: "AIGFutura";
}
</style>

<h2>AIG - FRANCISCO LOZANO</h2>

